version: "3.8"

services:
  db:
    image: postgres:16.3
    container_name: orderDB
    environment:
      POSTGRES_DB: orderDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - orders-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  orders-data: