services:
  db:
    image: postgres:16.3
    container_name: orderDB
    environment:
      POSTGRES_DB: orderDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - orders-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrate:
    image: harmanxze/order-app:latest
    command:
      [
        "./migrate",
        "-path",
        "/app/migrations",
        "-database",
        "postgres://admin:adminpassword@db:5432/orderDB?sslmode=disable",
        "up"
      ]
    depends_on:
      - db
    restart: "no"

  backend:
    image: harmanxze/order-app:latest
    container_name: order-app-container
    depends_on:
      - migrate
    ports:
      - "8080:8080"

volumes:
  orders-data: