version: "3.8"

services:
  db:
    image: postgres:16.3
    container_name: orderDB
    environment:
      POSTGRES_DB: orderDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - orders-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: harmanxze/order-app:latest
    container_name: order-app-container
    depends_on:
      - db
    ports:
      - "8080:8080"

  migrate:
    image: harmanxze/order-app:latest
    command: [ "./migrate/migrations" ]
    depends_on:
      - db
      
volumes:
  orders-data:
